### ISSUE TITLE
Buttons are overlapping each other.

### ISSUE THREAD

**Issue by blenkusha** [StoutCEE/fablab#12]
System buttons are displaying wrong by overlapping each other in the top right of the browser window. Believe this to be a problem with CSS defined values for button header. Reorient buttons to populate right side of header first, or change size of buttons so buttons do not overlap.

**Comment by MaximUltimatum** [comment]
Fixed this Tuesday March 20th with Christian - cycled through html button formats until buttons aligned nicely.
