### ISSUE TITLE
Records database needs to be created.

### ISSUE THREAD

**Issue by blenkusha** [StoutCEE/fablab#4]
We need a records database that is a printable database of user check-ins, check-outs and machine usage. This data is used to argue for funding for the lab and thus a record of everything must be accessible. We probably need a new database that is relational to the user database, and has fields populated by the check-in, check-out and machine pool scripts. THIS IS A VITAL FEATURE AND NEEDS TO BE ADDED IMMEDIATELY!

**Comment by MaximUltimatum** [comment]
Could we use a xcel spreadsheet for this? I could create a setup with user log/employees present/usage graphs. The card reader would have too send inputs to both xcel and the website. If we implemented it this way the website would keep track of people and machines, "live" data, and xcel could keep a log of who enters. Is this a good idea?
