### ISSUE TITLE
Add button for removal of machine entries into machine pool.

### ISSUE THREAD

**Issue by blenkusha** [StoutCEE/fablab#9]
Fabrication lab assistants (Duane’s students) should be able to add and remove machines to the database. Currently, the new machine button only adds a machine to the database. Adding a removal button might be handy?

**Comment by loerac** [comment]
For deleting a machine, do you want it to be deleted while the machine is being used or do you want it so the user has to wait until the machine is not being used?

**Comment by blenkusha** [comment]
It might be best to prevent a machine from being deleted while in use. After all, if they can force users off a machine with the checkout option, there's no reason they shouldn't do it before deleting a machine. I would also say we need some kind of control to prevent regular users from deleting a machine. Maybe a password or key code lock on it? Dunno.

**Comment by loerac** [comment]
I already made one that only the workers in the fablab can add/delete a machine. They swipe their card and then it lets them add/delete a machine

**Comment by loerac** [comment]
I got it done
